openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger dive n go
  license:
    name: MIT
servers:
  - url: http://localhost:3001
paths:
  /api/signup:
    post:
      summary: Register user
      operationId: UserRegistration
      tags:
        - signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - 'email'
                - 'password'
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: user details
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - email
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
